# ----------- CONFIGURABLE START -----------
title:            "Shuai Huang"
description:      "Machine Learning, Healthcare, and Systems Engineering"
url:              http://www.shuaihuang.info # Site url, without a slash at the end.
signoff:          "Shuai" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-52825511-2
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         About me
    url:          /
    external:     false
  - name:         Research
    url:          /research
    external:     false
  - name:         Publications
    url:          /publications
    external:     false
  - name:         Teaching
    url:          /teaching
    external:     false
  - name:         Service
    url:          /service
    external:     false
  - name:         Software
    url:          /software
    external:     false
  - name:         Students
    url:          /students
    external:     false
  - name:         CV
    url:          /CV
    external:     false
  
# ------------ CONFIGURABLE END ------------

#permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
